# 1. Model Configuration
model_size: 'n'          # Model size (n, s, m, l, x)
num_classes: 2           # Number of classes
input_channels: 1        # Number of input channels for the signal
input_length: 1024       # Input sequence length
# num_classes and input_length will be overridden by dataset_info.json

# 2. Data Configuration
dataset_path: 'sin_wave_dataset'  # Path to the generated dataset directory
num_workers: 4                    # Number of workers for DataLoader (0 for Windows)

# 3. Training Configuration
epochs: 100                       # Number of training epochs (增加训练轮数)
batch_size: 16                    # Batch size for training
learning_rate: 0.001             # Initial learning rate (降低学习率)
weight_decay: 0.0005              # Optimizer weight decay

# 4. Loss Function Hyperparameters (hyp)
hyp:
  box: 1.0              # IoU loss weight (降低边界框损失权重)
  cls: 3.0              # Classification loss weight
  dfl: 0.8              # Distribution Focal Loss weight

# 5. Additional Parameters
reg_max: 16              # DFL regression maximum value 